### ISSUE TITLE
Backwards incompatible change between 10.37 and 10.38

### ISSUE THREAD

**Issue by oerdnj** [PhilipHazel/pcre2#56]
When PHP is compiled with pcre2-10.39 (currently packaged version), but pcre2-10.36 (previously packaged version), there's a BC-break:

```
=== pcre2-10.35 ===
PHP Warning:  preg_match(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in Command line code on line 1
=== pcre2-10.36 ===
PHP Warning:  preg_match(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in Command line code on line 1
=== pcre2-10.37 ===
PHP Warning:  preg_match(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in Command line code on line 1
=== pcre2-10.38 ===
=== pcre2-10.39 ===
```

This breaks just too many things, so perhaps either the change need to be reverted/fixed or SONAME bumped.

I manually bisected the problem to be introduced in the 21c26698b3cd5ab33f70325ec17db99f431a94a0 commit:

```
ondrej@calcifer:~/Projects/tmp/pcre2 ((eea410b...))$
PHP Warning:  preg_match(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in Command line code on line 1
```

vs nothing printed here:

```
ondrej@calcifer:~/Projects/tmp/pcre2 ((21c2669...))$
```

e.g. PHP compiled with pcre2 that includes 21c26698b3cd5ab33f70325ec17db99f431a94a0 doesn't run without warning when linked with pcre2 that doesn't include 21c26698b3cd5ab33f70325ec17db99f431a94a0.

**Comment by oerdnj** [comment]
Ok, I see, this is really between hard place and a rock as PHP sources include this:

```
#ifdef PCRE2_EXTRA_ALLOW_LOOKAROUND_BSK
        /* pcre 10.38 needs PCRE2_EXTRA_ALLOW_LOOKAROUND_BSK, disabled by default */
#define PHP_PCRE_DEFAULT_EXTRA_COPTIONS PCRE2_EXTRA_ALLOW_LOOKAROUND_BSK
#else
#define PHP_PCRE_DEFAULT_EXTRA_COPTIONS 0
#endif
```

which makes any code compiled with 10.38+ incompatible when linked with < 10.38, but there's no way how to express that without bumping SONAME. Maybe we can somehow express that in Debian by hand.

What does @remicollet think?

**Comment by remicollet** [comment]
@oerdnj  If you have 10.38 at buildtime, how can you have something older at runtime ?

**Comment by oerdnj** [comment]
Debian buster have pcre 10.36, but the external repositories have 10.39 since @PhilipHazel does a good job at fixing functional bugs in the library I keep it up to date in the DEB.SURY.ORG repositories.

Unfortunately, some people don't do the full update+upgrade cycle when adding external repositories (they should, but ...), so the updated pcre2 doesn't get pulled in.

I think we can solve this in the pcre2 package by adding minimal version requirement to be 10.38 when `pcre2_set_compile_extra_options` is being used.

I don't know what mechanism RPM based distributions are using, but Debian (at least some better maintained libraries) have list of C symbols with corresponding version when they were introduced. However, this doesn't work here, because the options is actually only in the header and not a full symbol.

**Comment by nikic** [comment]
Maybe we need to address this on the PHP side using `pcre2_config` + `PCRE2_CONFIG_VERSION` to fetch the version of the linked library at runtime and set the flag based on that?

**Comment by remicollet** [comment]
> Unfortunately, some people don't do the full update+upgrade cycle when adding external repositories (they should, but ...), so the updated pcre2 doesn't get pulled in.

Usually cherry-picking updates is not supported (in RPM world), and cannot be

> have list of C symbols with corresponding version when they were introduced. 

Sadly very few libraries have a proper symbol versioning... (glibc, libxml, ...)

> I don't know what mechanism RPM based distributions are using, 

Mostly auto-dep on soname (and symbol versioning when exists).

In such case, I somtime use something like (to ensure version ar runtime > version at buildtime)

```
global buildver %(pkg-config --silence-errors --modversion libfoo >/dev/null || echo 65536)
Requires:       libfoo%{?_isa}  >= %{buildver}

```

**Comment by oerdnj** [comment]
> Maybe we need to address this on the PHP side using pcre2_config + PCRE2_CONFIG_VERSION to fetch the version of the linked library at runtime and set the flag based on that?

@nikic Is the flag even needed? Is there any documented failure or it was just a precaution to set it?

**Comment by nikic** [comment]
I believe there was a failure in our test suite.

**Comment by remicollet** [comment]
@nikic I really think this is a downstream issue, not a PHP one.

@oerdnj see ext/pcre/tests/bug70345.phpt, this one will fail with something like
`Compilation failed: \K is not allowed in lookarounds (but see PCRE2_EXTRA_ALLOW_LOOKAROUND_BSK)`

**Comment by carenas** [comment]
While I am sympathetic with the problem, I don't think there is a way to "fix" this in PCRE.

Yes. there was a "backwards incompatible" change in 10.38, but it was documented and a workaround for whoever might still need the old behaviour was provided and even suggested clearly in the error message.

PHP shouldn't had just enabled it so quickly to keep the test suite clean; IMHO the test should had been dropped or marked as not valid if using a newer PCRE, or a configuration added to enable the old behaviour that would set the flag as needed when PCRE is newer than 10.38 and added as a precondition to keep the test running ALSO for newer versions of PCRE.

The error shown in the report is how PCRE protects itself from unknown bits in the option flags that it doesn't know how to handle, and of course old versions of PCRE wouldn't know about this flag, or even need it because \K was not suppressed there, just like old versions of perl do before this same change was done there.

Yes; backward incompatible changes where the ABI/API changes need a version bump, but this is neither of those either.

**Comment by oerdnj** [comment]
> PHP shouldn't had just enabled it so quickly to keep the test suite clean

I kind of agree with this.  I think it would be better in following default pcre2 behavior.

That said, I think think it's time to close the issue here.

**Comment by nikic** [comment]
> PHP shouldn't had just enabled it so quickly to keep the test suite clean; IMHO the test should had been dropped or marked as not valid if using a newer PCRE, or a configuration added to enable the old behaviour that would set the flag as needed when PCRE is newer than 10.38 and added as a precondition to keep the test running ALSO for newer versions of PCRE.

We try to avoid behavior changes in patch releases. The thought here was that we should keep it enabled in already released stable versions and maybe disable in the next minor. We've done this in the past for other flag-controlled behavior changes in PCRE.

As we're already on the topic of this change, I'd really appreciate it if you could point me towards some information on why this change was made and how we can verify whether out matcher implementation is affected by this issue or not. The documentation only mentions the existence of the flag, and while #4 has more information, it also requires additional context to understand. Is there some example regex that illustrates the problem?

**Comment by PhilipHazel** [comment]
The change was made because Perl has done the same thing, but we did provide a backwards compatibility switch.
